"use strict";
(function(){
const KEY="JESSIE_NEXUS_V1",MS="2026-10-01",LS="2027-01-01",MUSIC="9nN9qMW4Fek";
const CURRICULUM=[
["Marketing Fundamentals",["Marketing vs Sales vs Branding","Market","Customer","Target Audience","Persona","Needs","Wants","Pain Points","Value Proposition","Positioning","USP","Competitors","Market Research","Customer Journey","Funnel","Awareness","Consideration","Conversion","Retention","B2B","B2C","Offer","Pricing Psychology","Customer Experience"]],
["Marketing Strategy",["Marketing Objectives","Market Segmentation","Targeting","Positioning Strategy","Marketing Mix","4Ps","7Ps","Competitive Strategy","Go-to-Market","Channel Strategy","Marketing Plan","Budgeting","Strategic Priorities"]],
["Branding",["Brand Purpose","Brand Mission","Brand Vision","Brand Values","Brand Personality","Brand Voice","Visual Identity","Brand Story","Brand Architecture","Brand Equity","Brand Consistency","Rebranding"]],
["Consumer Behavior",["Decision Making","Psychology of Buying","Emotions","Motivation","Social Proof","Trust","Cognitive Biases","Perceived Value","Customer Research","Behavioral Segmentation","Customer Experience"]],
["Content Marketing",["Content Strategy","Content Pillars","Audience Research","Content Formats","Storytelling","Hooks","Copywriting Basics","Editorial Calendar","SEO Content","Distribution","Repurposing","Content Measurement"]],
["Social Media Marketing",["Platform Strategy","Organic Growth","Community Building","Engagement","Instagram Strategy","TikTok Strategy","LinkedIn Strategy","Social Copy","Social Analytics","Influencer Marketing","Social Campaigns"]],
["Digital Marketing",["Digital Ecosystem","SEO","SEM","Email Marketing","Landing Pages","Conversion Rate Optimization","Funnels","Retargeting","Affiliate Marketing","Digital Strategy"]],
["Advertising",["Advertising Fundamentals","Campaign Objectives","Creative Strategy","Ad Copy","Creative Testing","Audience Targeting","Meta Ads","Google Ads","Budget Allocation","CAC","ROAS","Attribution"]],
["Analytics",["Marketing Metrics","KPIs","North Star Metric","Traffic","Conversion Rate","CAC","LTV","ROAS","Funnel Analytics","Dashboards","Experiments","A/B Testing","Data Interpretation"]],
["CRM & Retention",["CRM Fundamentals","Lead Management","Customer Lifecycle","Email Flows","Segmentation","Retention Strategy","Churn","Loyalty","Lifecycle Campaigns","Personalization","Customer Value"]],
["Growth",["Growth Loops","Growth Mindset","Acquisition","Activation","Retention","Referral","Experimentation","Growth Metrics","Product-Led Growth","Virality","Growth Planning"]],
["Marketing Management",["Marketing Leadership","Team Structure","Agency Management","Campaign Planning","Resource Allocation","Marketing Operations","Stakeholder Management","Reporting","Risk Management","Integrated Campaigns","Strategic Review"]]];
const TOPICS=[];CURRICULUM.forEach((s,a)=>s[1].forEach((n,b)=>TOPICS.push({id:"m"+a+"-"+b,section:s[0],name:n,minutes:25})));
const GOALS=[
["fin40","FINANCE","40,000 EGP starting capital",40000,"EGP"],["save10","FINANCE","10,000 EGP side savings fund",10000,"EGP"],["emergency10","FINANCE","10,000 EGP expense emergency reserve",10000,"EGP"],["car100","FINANCE","100,000 EGP vehicle down payment",100000,"EGP"],["moneyfellows","FINANCE","Money Fellows toward 1,000,000 EGP",1000000,"EGP"],["budget","FINANCE","Daily spending + budget",100,"%"],["debt","FINANCE","Reduce borrowing + repay debts",100,"%"],["rewards","FINANCE","Personal rewards without harming savings",100,"%"],
["dm1","EDUCATION","Digital Marketing Course 1 — 12 sessions",12,"sessions"],["dm2","EDUCATION","Digital Marketing Diploma 2 — 4 sessions",4,"sessions"],["dmpro","EDUCATION","Digital Marketing basics → advanced",100,"%"],["design","EDUCATION","Graphic Design + practical application",100,"%"],["wedding","WEDDING","Wedding Planning Diploma / Course",5000,"EGP"],["cyber","TECH","Ethical Hacking / Cybersecurity",100,"%"],["website","TECH","Build websites from scratch + AI",100,"%"],["aihr","TECH","AI + HR Diplomas in H1",4000,"EGP"],["aieng","TECH","AI Engineering + Humanoid Diploma in H2",8000,"EGP"],["ai","TECH","Advanced practical AI systems",100,"%"],
["english","LANGUAGES","Super English",100,"%"],["italian","LANGUAGES","Italian every day for 365 days",365,"days"],["drivecar","DRIVING","Learn car driving",8000,"EGP"],["drivebike","DRIVING","Learn motorcycle riding",4000,"EGP"],
["wardrobe","STYLE","Full wardrobe refresh",100,"%"],["bag","STYLE","Travel bag",6000,"EGP"],["hair","STYLE","New hairstyle",6000,"EGP"],["laser","STYLE","Start laser",4000,"EGP"],
["vibebrand","THE VIBE B","Luxury Wedding Planner brand",100,"%"],["vibelogo","THE VIBE B","Unconventional logo + identity",100,"%"],["vibeapply","THE VIBE B","Apply learning directly to The Vibe B",100,"%"],["instagram","THE VIBE B","Professional Instagram + digital presence",100,"%"],
["name","ADMIN","Study changing name / title",15000,"EGP"],["passport","ADMIN","Passport after name / title change",10000,"EGP"],["lifeos","SYSTEM","Goal → Milestones → Monthly → Weekly → Daily",100,"%"],["birthday","PERSONAL","February birthday plan",100,"%"]];
const PHASES=[["Foundation",1,30,"pronunciation, greetings, numbers, basic phrases, essere / avere"],["A1 Core",31,90,"articles, gender, present tense, family, routines, food, directions"],["A1 Consolidation",91,150,"past basics, listening, reading, short writing, conversation"],["A2 Core",151,210,"passato prossimo, imperfect foundations, pronouns, travel"],["A2 Expansion",211,270,"longer listening, opinions, connectors, problem solving"],["B1 Foundation",271,330,"narration, opinions, explanations, workplace/travel language"],["B1 Consolidation",331,365,"conversation, presentations, writing, AI conversations"]];
const MONTHS=[
["JAN","RESET / STYLE / FOUNDATIONS",["wardrobe","bag","hair","laser","wedding","vibelogo"]],["FEB","BIRTHDAY / WEDDING / BRAND",["birthday","wedding","vibelogo","vibebrand","instagram"]],["MAR","MARKETING APPLICATION / DESIGN",["dm1","dm2","dmpro","design","vibeapply"]],["APR","CYBERSECURITY / DRIVING",["cyber","drivecar","drivebike","english"]],["MAY","WEBSITE / WEB SECURITY",["website","cyber","ai","vibeapply"]],["JUN","MID-YEAR CONSOLIDATION",["cyber","english","dmpro","vibebrand","lifeos"]],["JUL","AI ENGINEERING H2",["aieng","ai","website","cyber"]],["AUG","AI + VIBE B SYSTEMS",["aieng","ai","vibebrand","instagram"]],["SEP","GROWTH / ANALYTICS / PORTFOLIO",["dmpro","vibeapply","instagram","website","design"]],["OCT","DRIVING / TECHNICAL EXECUTION",["drivecar","drivebike","website","cyber","ai"]],["NOV","FINANCE / ADMIN / STABILITY",["fin40","save10","emergency10","car100","debt","name","passport"]],["DEC","CLOSEOUT / 2028 LAUNCH",["fin40","save10","emergency10","moneyfellows","lifeos","vibebrand","ai"]]];
const VIBE=[["SIGNATURE","Key symbol + luxury positioning"],["IDENTITY","Logo + visual language"],["OFFER","Wedding planning architecture"],["PRESENCE","Instagram + digital home"],["AUTHORITY","Content + marketing engine"],["EXPERIENCE","Premium client system"]];
function seed(){return{done:{},life:{},rewards:[],daily:2}}let S=load(),view="dashboard";
function load(){try{return Object.assign(seed(),JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){return seed()}}function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function esc(x){return String(x==null?"":x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function date(){let q=new URLSearchParams(location.search).get("date");return q&&/^\\d{4}-\\d\\d-\\d\\d$/.test(q)?q:new Date().toISOString().slice(0,10)}
function dt(s){let a=s.split("-").map(Number);return new Date(a[0],a[1]-1,a[2])}function diff(a,b){return Math.floor((dt(b)-dt(a))/864e5)}function day(){return Math.max(1,diff(LS,date())+1)}
function pct(n){return Math.max(0,Math.min(100,Math.round(n||0)))}function gv(id){return Number(S.life[id]||0)}
function gp(g){return g[0]==="italian"?pct(Math.max(gv("italian"),date()>=LS?Math.min(365,day()):0)/365*100):pct(gv(g[0])/(g[3]||100)*100)}
function mp(){return pct(TOPICS.filter(t=>S.done[t.id]).length/TOPICS.length*100)}
function cat(c){let a=GOALS.filter(g=>g[1]===c);return pct(a.reduce((n,g)=>n+gp(g),0)/(a.length||1))}
function phase(){let d=day();return PHASES.find(p=>d>=p[1]&&d<=p[2])||PHASES[6]}
function skill(){return["Vocabulary","Grammar","Listening","Speaking","Reading","Writing","AI Conversation"][(day()-1)%7]}
function month(){return MONTHS[dt(date()).getMonth()]||MONTHS[0]}
function monthFocus(){return["Audit wardrobe and set budget.","Start Wedding Planning and build birthday plan.","Turn Marketing lessons into Vibe B assets.","Build cybersecurity + driving foundations.","Ship website + security improvements.","Consolidate skills and audit the brand.","Launch AI Engineering track.","Build AI/Vibe B systems.","Measure growth and portfolio.","Execute driving + technical milestones.","Stabilize finance + admin.","Close 2027 and design 2028."][dt(date()).getMonth()]}
function missions(){
let a=TOPICS.filter(t=>!S.done[t.id]).slice(0,Number(S.daily)||2).map(t=>({id:"m-"+t.id,title:t.name,detail:t.section+" · practical Marketing action",min:t.minutes}));
if(date()>=LS){let d=day();a.push({id:"it-"+d,title:d%7===0?"Italian weekly review + AI conversation":"Italian · "+skill(),detail:"Day "+d+" · "+phase()[0]+" · "+phase()[3],min:d%7===0?40:25});let m=month();let gid=m[2][Math.floor((d-1)/7)%m[2].length];let g=GOALS.find(x=>x[0]===gid);a.push({id:"life-"+d,title:m[0]+" · "+["PLAN","LEARN","PRACTICE","BUILD","APPLY","REVIEW","WEEKLY REVIEW"][(d-1)%7],detail:"Advance: "+(g?g[2]:"the life system")+" · "+monthFocus(),min:30})}return a}
function done(id){return!!S.done[id]}
function finish(id,title){if(done(id))return;S.done[id]=Date.now();S.rewards.unshift({date:date(),title:title});save();toast("COMPLETED · REWARD UNLOCKED");modal("<span class='eyebrow'>REWARD PROTOCOL</span><h3>"+esc(title)+"</h3><p>Your action moved the system forward. Pick one intentional reward.</p><div class='card reward'><b>✦ 20-minute guilt-free break</b><p>Or a favorite drink, self-care, or bank the reward budget for a larger milestone.</p></div><button class='action' data-act='close'>CONTINUE</button>");render(view)}
function toast(x){let t=document.getElementById("toast");t.textContent=x;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2200)}
function modal(x){document.getElementById("modalCard").innerHTML=x;document.getElementById("modal").classList.remove("hidden")}function close(){document.getElementById("modal").classList.add("hidden")}
function stat(a,b,c,k){return"<div class='card stat'><small>"+esc(a)+"</small><b class='"+(k||"")+"'>"+esc(b)+"</b><span>"+esc(c)+"</span></div>"}
function goal(g){let p=gp(g);return"<div class='card goal'><span class='tag'>"+esc(g[1])+"</span><h4>"+esc(g[2])+"</h4><div class='progress'><i style='width:"+p+"%'></i></div><div class='ptext'><span>"+gv(g[0]).toLocaleString()+" / "+g[3].toLocaleString()+" "+esc(g[4])+"</span><b>"+p+"%</b></div><button class='action' data-act='goal' data-id='"+g[0]+"'>UPDATE</button></div>"}
function task(t){let d=done(t.id);return"<div class='card mission'><button class='check "+(d?"done":"")+"' data-act='done' data-id='"+esc(t.id)+"' data-title='"+esc(t.title)+"'>"+(d?"✓":"")+"</button><div class='mission-main'><b>"+esc(t.title)+"</b><span>"+esc(t.detail)+"</span></div><span class='pill'>"+t.min+" MIN</span></div>"}
function dashboard(){let m=missions(),p=month();return"<div class='card hero'><span class='eyebrow'>NEXUS COMMAND / "+(date()<LS?"2027 PREVIEW":"DAY "+day())+"</span><h1>Make the <em>next move</em> obvious.</h1><p>"+esc(m[0]?m[0].title:"System review")+" · "+esc(m[0]?m[0].detail:"Review your systems and prepare tomorrow.")+"</p><button class='action' data-act='nav' data-id='missions'>EXECUTE TODAY →</button><div class='hero-orbit'></div></div><div class='section-title'><h3>System telemetry</h3><span>LIVE</span></div><div class='grid g4'>"+stat("MARKETING",mp()+"%","145 topics","cyan")+stat("LANGUAGES",cat("LANGUAGES")+"%","English + Italian","violet")+stat("THE VIBE B",cat("THE VIBE B")+"%","Luxury Wedding Planner","pink")+stat("FINANCE",cat("FINANCE")+"%","Capital / savings / reserve","gold")+"</div><div class='section-title'><h3>Today</h3><span>"+m.length+" NODES</span></div><div class='grid g2'>"+m.slice(0,4).map(task).join("")+"</div><div class='section-title'><h3>Current vector</h3><span>"+p[0]+"</span></div><div class='grid g3'>"+stat("MONTH",p[1],"Primary vector","cyan")+stat("WEEK","W"+(Math.floor((dt(date()).getDate()-1)/7)+1),monthFocus(),"violet")+stat("EVOLUTION",mp()<10?"DORMANT":mp()<25?"PRESENCE":mp()<50?"FORMING":mp()<75?"BODY ONLINE":"AWAKENED","Marketing engine","lime")+"</div>"}
function missionsPage(){let m=missions();return"<div class='card hero'><span class='eyebrow'>MISSION CONTROL</span><h1>Today has a <em>small surface.</em></h1><p>The system can hold huge ambitions. You only execute the next nodes.</p></div><div class='section-title'><h3>Queue</h3><span>"+m.length+" ACTIONS</span></div><div class='grid g2'>"+m.map(task).join("")+"</div>"}
function life(){return"<div class='card hero'><span class='eyebrow'>2027 LIFE MAP</span><h1>One year. <em>Many worlds.</em></h1><p>Financial stability, education, languages, technology, driving, style, Wedding Planning, The Vibe B, admin and personal milestones are coordinated here.</p></div><div class='section-title'><h3>12-month architecture</h3><span>GOAL → MONTH → WEEK → DAY</span></div><div class='grid g3'>"+MONTHS.map((m,i)=>"<div class='card goal'><span class='tag'>"+m[0]+"</span><h4>"+m[1]+"</h4><p>"+monthFocusFor(i)+"</p><button class='action' data-act='month' data-id='"+i+"'>VIEW VECTOR</button></div>").join("")+"</div><div class='section-title'><h3>Goal constellation</h3><span>"+GOALS.length+" GOALS</span></div><div class='grid g3'>"+GOALS.map(goal).join("")+"</div>"}
function monthFocusFor(i){return["Style reset, Wedding research and identity foundations.","Birthday, Wedding Planning and brand identity.","Marketing application and Graphic Design.","Cybersecurity and driving foundations.","Website building and web security.","Mid-year consolidation.","AI Engineering H2 launch.","AI Engineering + Vibe B systems.","Growth, analytics and portfolio.","Driving and technical execution.","Finance, admin and stability.","2027 closeout and 2028 launch."][i]}
function marketing(){return"<div class='card hero'><span class='eyebrow'>MARKETING ENGINE / ACTIVE 01 OCT 2026</span><h1>145 topics.<br><em>Built to be applied.</em></h1><p>Fundamentals → strategy → branding → consumer behavior → content → social → digital → advertising → analytics → CRM → growth → management.</p><div class='big-number cyan'>"+mp()+"%</div><div class='progress'><i style='width:"+mp()+"%'></i></div></div><div class='section-title'><h3>Curriculum</h3><span>"+TOPICS.filter(t=>S.done[t.id]).length+" / "+TOPICS.length+"</span></div><div class='grid g2'>"+CURRICULUM.map((s,i)=>{let ts=TOPICS.filter(t=>t.section===s[0]),d=ts.filter(t=>S.done[t.id]).length;return"<div class='card'><span class='tag'>"+String(i+1).padStart(2,"0")+"</span><h3>"+esc(s[0])+"</h3><div class='progress'><i style='width:"+pct(d/ts.length*100)+"%'></i></div><div class='ptext'><span>"+d+" / "+ts.length+"</span><b>"+pct(d/ts.length*100)+"%</b></div><div class='topic-list'>"+ts.map(t=>"<div class='topic'><span>"+esc(t.name)+"</span><button class='action' data-act='mkt' data-id='"+t.id+"'>"+(S.done[t.id]?"DONE":"DO")+"</button></div>").join("")+"</div></div>"}).join("")+"</div>"}
function italian(){let p=phase();return"<div class='card hero'><span class='eyebrow'>ITALIAN / 365-DAY ARC</span><h1>Build a <em>real language.</em></h1><p>Daily skill rotation + weekly review + AI conversation. Foundation → A1 → A2 → B1 foundation.</p><div class='grid g3'>"+stat("DAY",date()>=LS?day():"PREVIEW","of 365","cyan")+stat("PHASE",p[0],p[3],"violet")+stat("SKILL",date()>=LS?skill():"READY","daily block","lime")+"</div></div><div class='section-title'><h3>Phase map</h3><span>365 DAYS</span></div><div class='grid g2'>"+PHASES.map(x=>"<div class='phase "+(x[0]===p[0]?"current":"")+"'><b>"+x[0]+" · DAYS "+x[1]+"–"+x[2]+"</b><span>"+esc(x[3])+"</span></div>").join("")+"</div><div class='section-title'><h3>Skill wheel</h3><span>7-DAY LOOP</span></div><div class='grid g4'>"+["Vocabulary","Grammar","Listening","Speaking","Reading","Writing","AI Conversation"].map((x,i)=>stat("DAY "+(i+1),x,"Practice + evidence","cyan")).join("")+"</div>"}
function vibe(){return"<div class='card hero'><span class='eyebrow'>THE VIBE B / DARK LUXURY WEDDING PLANNER</span><h1>The <em>key</em> opens the brand.</h1><p>Use the key as the core metaphor: access, trust, entrance, transformation and a new chapter. The brand grows from symbol → identity → offer → presence → authority → experience.</p></div><div class='grid g3'>"+VIBE.map((v,i)=>"<div class='card goal'><span class='tag'>0"+(i+1)+"</span><h4>"+v[0]+"</h4><p>"+v[1]+"</p><div class='progress'><i style='width:"+((i+1)*16.6)+"%'></i></div></div>").join("")+"</div><div class='section-title'><h3>Direct application</h3><span>LEARN → BUILD</span></div><div class='grid g2'><div class='card'><span class='eyebrow'>MARKETING</span><h3>Every lesson becomes a Vibe B asset.</h3><p class='muted'>Positioning → offer. Branding → identity. Content → Instagram. Analytics → measurement. Growth → acquisition.</p></div><div class='card'><span class='eyebrow'>DESIGN</span><h3>Premium, not beginner-looking.</h3><p class='muted'>Dark space, controlled typography, key symbolism, premium imagery and a system that scales beyond Instagram.</p></div></div>"}
function finance(){return"<div class='card hero'><span class='eyebrow'>FINANCE CONTROL</span><h1>Give every pound a <em>job.</em></h1><p>Separate capital, side savings, emergency reserve, vehicle fund, debt reduction and rewards. The OS tracks the target; you control the actual money.</p></div><div class='grid g4'>"+GOALS.filter(g=>g[1]==="FINANCE").slice(0,4).map(g=>stat(g[2],gv(g[0]).toLocaleString()+" "+g[4],gp(g)+"% of target","gold")).join("")+"</div><div class='section-title'><h3>Financial buckets</h3><span>UPDATE</span></div><div class='grid g2'>"+GOALS.filter(g=>g[1]==="FINANCE").map(goal).join("")+"</div>"}
function progress(){let avg=pct(GOALS.reduce((n,g)=>n+gp(g),0)/GOALS.length);return"<div class='grid g4'>"+stat("MARKETING",mp()+"%","145 topics","cyan")+stat("LIFE",avg+"%","all goals","violet")+stat("MISSIONS",Object.keys(S.done).length,"completed actions","lime")+stat("REWARDS",S.rewards.length,"earned moments","gold")+"</div><div class='section-title'><h3>Category telemetry</h3><span>LIVE</span></div><div class='grid g3'>"+["FINANCE","EDUCATION","TECH","LANGUAGES","DRIVING","STYLE","THE VIBE B","ADMIN","SYSTEM","PERSONAL"].map(c=>stat(c,cat(c)+"%","goal constellation","cyan")).join("")+"</div>"}
function settings(){return"<div class='card hero'><span class='eyebrow'>SYSTEM SETTINGS</span><h1>Shape the <em>machine.</em></h1><p>Everything is stored locally in this browser. Marketing pacing can be changed without changing the curriculum.</p></div><div class='grid g2'><div class='card'><span class='eyebrow'>MARKETING PACE</span><h3>Topics per day</h3><input id='daily' type='number' min='1' max='10' value='"+S.daily+"'><button class='action' data-act='save'>SAVE</button><p class='muted'>Default: 2/day.</p></div><div class='card'><span class='eyebrow'>DATA</span><h3>Your progress is yours.</h3><button class='action' data-act='export'>EXPORT JSON</button><button class='action' data-act='reset'>RESET</button><p class='muted'>Export before resetting.</p></div></div>"}
const P={dashboard:dashboard,missions:missionsPage,life:life,marketing:marketing,italian:italian,vibe:vibe,finance:finance,progress:progress,settings:settings};
const N={dashboard:"Nexus Command",missions:"Today's Missions",life:"2027 Life Map",marketing:"Marketing Engine",italian:"Italian Arc",vibe:"The Vibe B",finance:"Finance Control",progress:"Progress",settings:"Settings"};
function render(v){view=v||view;document.getElementById("view").innerHTML=P[view]();document.getElementById("pageTitle").textContent=N[view];document.getElementById("eyebrow").textContent="JESSIE / "+view.toUpperCase();document.getElementById("dateChip").textContent=date().slice(0,7);document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));document.getElementById("evo").textContent=mp()<10?"DORMANT":mp()<25?"PRESENCE":mp()<50?"FORMING":mp()<75?"BODY ONLINE":"AWAKENED";document.getElementById("evoBar").style.width=mp()+"%";document.getElementById("evoPct").textContent=mp()+"%"}
document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>render(b.dataset.view));
document.getElementById("view").onclick=function(e){let b=e.target.closest("[data-act]");if(!b)return;let a=b.dataset.act,id=b.dataset.id;
if(a==="nav"){render(id)}
else if(a==="done"){finish(id,b.dataset.title)}
else if(a==="mkt"){let t=TOPICS.find(x=>x.id===id);if(t)finish("m-"+id,t.name)}
else if(a==="goal"){let g=GOALS.find(x=>x[0]===id),v=prompt("Current progress for "+g[2]+" ("+g[4]+")",String(gv(id)));if(v!==null){S.life[id]=Math.max(0,Number(v)||0);save();render(view);toast("PROGRESS SYNCED")}}
else if(a==="month"){let m=MONTHS[Number(id)];modal("<span class='eyebrow'>2027 / "+m[0]+"</span><h3>"+m[1]+"</h3><p>Focus goals:</p><div class='timeline'>"+m[2].map(x=>{let g=GOALS.find(z=>z[0]===x);return"<div class='timeline-item'><b>"+(g?g[2]:x)+"</b><small>"+monthFocusFor(Number(id))+"</small></div>"}).join("")+"</div><button class='action' data-act='close'>CLOSE</button>")}
else if(a==="close"){close()}
else if(a==="save"){S.daily=Math.max(1,Math.min(10,Number(document.getElementById("daily").value)||2));save();toast("PACE SAVED");render(view)}
else if(a==="export"){let blob=new Blob([JSON.stringify(S,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="jessie-nexus-backup.json";a.click();URL.revokeObjectURL(u)}
else if(a==="reset"){if(confirm("Reset local JESSIE NEXUS progress?")){S=seed();save();render("dashboard");toast("SYSTEM RESET")}}};
document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")close()};
function startAudio(){let f=document.getElementById("yt");f.src="https://www.youtube.com/embed/"+MUSIC+"?autoplay=1&loop=1&playlist="+MUSIC+"&controls=0&playsinline=1"}
window.launchNexus=function(){document.getElementById("boot").classList.add("hidden");document.getElementById("app").classList.remove("hidden");document.getElementById("audioDock").classList.remove("hidden");startAudio();render("dashboard");toast("NEXUS ONLINE")};
window.toggleAudio=function(){let f=document.getElementById("yt");if(f.src){f.src="";document.getElementById("audioBtn").textContent="♫";toast("AUDIO OFF")}else{startAudio();document.getElementById("audioBtn").textContent="Ⅱ";toast("AUDIO ON")}};
window.closeModal=close;window.navigate=render;
document.getElementById("audioDock").querySelector("button").onclick=window.toggleAudio;
document.getElementById("audioBtn").onclick=window.toggleAudio;
document.getElementById("clock").textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});
setInterval(()=>{let c=document.getElementById("clock");if(c)c.textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})},1000);
render("dashboard");
})();